name: nyoom
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  ntp: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/data/
  - .env
  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/albertsans/albertsans1_thin.ttf
          weight: 100
        - asset: assets/fonts/albertsans/albertsans2_extralight.ttf
          weight: 200
        - asset: assets/fonts/albertsans/albertsans3_light.ttf
          weight: 300
        - asset: assets/fonts/albertsans/albertsans4_regular.ttf
          weight: 400
        - asset: assets/fonts/albertsans/albertsans5_medium.ttf
          weight: 500
        - asset: assets/fonts/albertsans/albertsans6_semibold.ttf
          weight: 600
        - asset: assets/fonts/albertsans/albertsans7_bold.ttf
          weight: 700
        - asset: assets/fonts/albertsans/albertsans8_extrabold.ttf
          weight: 800
        - asset: assets/fonts/albertsans/albertsans9_black.ttf
          weight: 900
